VKIDClientSecret=IreDnCeU18ejMsCzzEA4
VKIDClientID=54410856

storeFile = /Users/zoer/Documents/key_store
storePassword = Zoer.1639
keyAlias = ZCompanyAppKey
keyPassword = Zoer.1639

MERCHANT_LOGIN=LOCO_DRIVER_SHOP
PASSWORD_1=g1hybfLQChf4e508yRIX
PASSWORD_2=lGOmC8y1iNRbJ9M1fA3w