package com.z_company.route.viewmodel

data class SalaryCalculationUIState(
    val month: String = "",
    val tariffRate: Double? = null,
    val normaHours: Int? = null,
    val totalWorkTime: Long? = null,
    val paymentAtTariffHours: Long? = null,
    val paymentAtTariffMoney: Double? = null,
    val paymentAtPassengerHours: Long? = null,
    val paymentAtPassengerMoney: Double? = null,
    val paymentAtSingleLocomotiveHours: Long? = null,
    val paymentAtSingleLocomotiveMoney: Double? = null,
    val paymentHolidayHours: Long? = null,
    val paymentHolidayMoney: Double? = null,
    val surchargeHolidayHours: Long? = null,
    val surchargeHolidayMoney: Double? = null,
    val paymentAtOvertimeHours: Long? = null,
    val paymentAtOvertimeMoney: Double? = null,
    val surchargeAtOvertime05Hours: Long? = null,
    val surchargeAtOvertime05Money: Double? = null,
    val surchargeAtOvertimeHours: Long? = null,
    val surchargeAtOvertimeMoney: Double? = null,
    val zonalSurchargePercent: Double? = null,
    val zonalSurchargeMoney: Double? = null,
    val surchargeQualificationClassPercent: Double? = null,
    val surchargeQualificationClassMoney: Double? = null,
    val surchargeExtendedServicePhaseHour: Long? = null,
    val surchargeExtendedServicePhasePercent: Double? = null,
    val surchargeExtendedServicePhaseMoney: Double? = null,
    val surchargeHeavyLongDistanceTrainsHour: Long? = null,
    val surchargeHeavyLongDistanceTrainsPercent: Double? = null,
    val surchargeHeavyLongDistanceTrainsMoney: Double? = null,
    val paymentAtTimeOfWorkLong: Long? = null,
    val paymentAtTimeOfWorkMoney: Double? = null,
    val paymentNightTimeHours: Long? = null,
    val paymentNightTimePercent: Double? = null,
    val paymentNightTimeMoney: Double? = null,
    val totalChargedMoney: Double? = null,
    val retentionNdfl: Double? = null,
    val unionistsRetention: Double? = null,
    val otherRetention: Double? = null,
    val totalRetention: Double? = null,
    val toBeCredited: Double? = null
)