package com.z_company.route.viewmodel

import com.z_company.core.ResultState

data class SalaryCalculationUIState(
    val screenState: ResultState<Unit> = ResultState.Loading(),
    val month: String = "",
    // Индекс месяца (0-based) и год расчёта — для заголовка «Июль 2026» и стрелок
    // переключения месяца на экране (как на главном).
    val monthIndex: Int? = null,
    val year: Int? = null,
    val currency: String = "₽",
    val tariffRate: String? = null,
    val normaHours: Int? = null,
    val totalWorkTime: Long? = null,
    val paymentAtTariffHours: Long? = null,
    val paymentAtTariffMoney: Double? = null,
    val paymentAtPassengerHours: Long? = null,
    val paymentAtPassengerMoney: Double? = null,
    val paymentAtSingleLocomotiveHours: Long? = null,
    val paymentAtSingleLocomotiveMoney: Double? = null,
    val paymentHolidayHours: Long? = null,
    val paymentHolidayMoney: Double? = null,
    val surchargeHolidayHours: Long? = null,
    val surchargeHolidayMoney: Double? = null,
    val paymentAtOvertimeHours: Long? = null,
    val paymentAtOvertimeMoney: Double? = null,
    val surchargeAtOvertime05Hours: Long? = null,
    val surchargeAtOvertime05Money: Double? = null,
    val surchargeAtOvertimeHours: Long? = null,
    val surchargeAtOvertimeMoney: Double? = null,
    val zonalSurchargePercent: Double? = null,
    val zonalSurchargeMoney: Double? = null,
    val surchargeQualificationClassPercent: Double? = null,
    val surchargeQualificationClassMoney: Double? = null,
    val linearMileageDistance: Double? = null,
    val linearMileageMoney: Double? = null,
    val linearMileageAccruals: List<LinearMileageAccrual> = emptyList(),
    val surchargeExtendedServicePhaseHour: List<Long?> = emptyList(),
    val surchargeExtendedServicePhasePercent: List<String?> = emptyList(),
    val surchargeExtendedServicePhaseMoney: List<Double?> = emptyList(),
    val surchargeHeavyTransHour: List<Long?> = emptyList(),
    val surchargeHeavyTransPercent: List<String?> = emptyList(),
    val surchargeHeavyTransMoney: List<Double?> = emptyList(),
    val surchargeLongTrainHour: List<Long?> = emptyList(),
    val surchargeLongTrainPercent: List<String?> = emptyList(),
    val surchargeLongTrainMoney: List<Double?> = emptyList(),
    val surchargeHeavyLongDistanceTrainsHours: Long? = null,
    val surchargeHeavyLongDistanceTrainsPercent: Double? = null,
    val surchargeHeavyLongDistanceTrainsMoney: Double? = null,
    val surchargeDoubledTrainFirstHours: Long? = null,
    val surchargeDoubledTrainFirstMoney: Double? = null,
    val surchargeDoubledTrainSecondHours: Long? = null,
    val surchargeDoubledTrainSecondMoney: Double? = null,
    val paymentAtTimeOfWorkLong: Long? = null,
    val paymentAtTimeOfWorkMoney: Double? = null,
    val paymentNightTimeHours: Long? = null,
    val paymentNightTimePercent: Double? = null,
    val paymentNightTimeMoney: Double? = null,
    val nordicSurchargePercent: Double? = null,
    val nordicSurchargeMoney: Double? = null,
    val districtSurchargeCoefficient: Double? = null,
    val districtSurchargeMoney: Double? = null,
    val onePersonOperationHours: Long? = null,
    val onePersonOperationPercent: Double? = null,
    val onePersonOperationMoney: Double? = null,
    val onePersonOperationPassengerTrainHours: Long? = null,
    val onePersonOperationPassengerTrainPercent: Double? = null,
    val onePersonOperationPassengerTrainMoney: Double? = null,
    val restInExcessOfTheNormTime: Long? = null,
    val restInExcessOfTheNormMoney: Double? = null,
    val harmfulnessSurchargePercent: Double? = null,
    val harmfulnessSurchargeMoney: Double? = null,
    val averagePaymentHours: Long? = null,
    val averagePaymentMoney: Double? = null,
    val underworkHours: Long? = null,
    val underworkMoney: Double? = null,
    // Отработано меньше нормы, но средний час в настройках не задан →
    // показать инфо-окно с предложением указать его.
    val showSetAverageHourInfo: Boolean = false,
    val caringForDisableChildrenHours: Long? = null,
    val caringForDisableChildrenMoney: Double? = null,
    val businessTripHours: Long? = null,
    val businessTripMoney: Double? = null,
    val technicalStudyHours: Long? = null,
    val technicalStudyMoney: Double? = null,
    val totalChargedMoney: Double? = null,
    val retentionNdfl: Double? = null,
    val unionistsRetention: Double? = null,
    val otherSurchargeMoney: Double? = null,
    val otherSurchargePercent: Double? = null,
    val otherRetention: Double? = null,
    val welfareRetention: Double? = null,
    val alimonyRetention: Double? = null,
    val totalRetention: Double? = null,
    val toBeCredited: Double? = null
)
