com.z_company.domain.entities.route.Route
com.z_company.domain.entities.route.BasicData
com.z_company.domain.entities.route.Locomotive
com.z_company.domain.entities.route.Train
com.z_company.domain.entities.route.Passenger
com.z_company.domain.entities.route.Photo
